Repository inventree/inventree-app, pull requests merged in 2025-06, with the labels that each got.

#636 New Crowdin updates
  lib/l10n/de_DE/app_de_DE.arb
  lib/l10n/fa_IR/app_fa_IR.arb
  lib/l10n/fr_FR/app_fr_FR.arb
  lib/l10n/it_IT/app_it_IT.arb
  lib/l10n/nl_NL/app_nl_NL.arb
  lib/l10n/pl_PL/app_pl_PL.arb
  lib/l10n/ru_RU/app_ru_RU.arb
  lib/l10n/sv_SE/app_sv_SE.arb
  lib/l10n/tr_TR/app_tr_TR.arb
  lib/l10n/zh_CN/app_zh_CN.arb
Labels: translation

#651 Barcode scan refactor
  .github/workflows/android.yaml
  .github/workflows/ci.yaml
  .github/workflows/ios.yaml
  android/app/build.gradle
  android/app/src/profile/AndroidManifest.xml
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.properties
  android/settings.gradle
  assets/release_notes.md
  ios/Flutter/ephemeral/flutter_lldb_helper.py
  ios/Flutter/ephemeral/flutter_lldbinit
  lib/barcode/camera_controller.dart
  lib/barcode/wedge_controller.dart
  lib/l10.dart
  lib/l10n/app_en.arb
  lib/main.dart
  lib/widget/home.dart
  pubspec.lock
  pubspec.yaml
  test/fixtures/barcodes/test_sheet.png
Labels: bug, enhancement, barcode

#652 New Crowdin updates
  lib/l10n/ar_SA/app_ar_SA.arb
  lib/l10n/bg_BG/app_bg_BG.arb
  lib/l10n/cs_CZ/app_cs_CZ.arb
  lib/l10n/da_DK/app_da_DK.arb
  lib/l10n/de_DE/app_de_DE.arb
  lib/l10n/el_GR/app_el_GR.arb
  lib/l10n/es_ES/app_es_ES.arb
  lib/l10n/es_MX/app_es_MX.arb
  lib/l10n/et_EE/app_et_EE.arb
  lib/l10n/fa_IR/app_fa_IR.arb
  lib/l10n/fi_FI/app_fi_FI.arb
  lib/l10n/fr_FR/app_fr_FR.arb
  lib/l10n/he_IL/app_he_IL.arb
  lib/l10n/hi_IN/app_hi_IN.arb
  lib/l10n/hu_HU/app_hu_HU.arb
  lib/l10n/id_ID/app_id_ID.arb
  lib/l10n/it_IT/app_it_IT.arb
  lib/l10n/ja_JP/app_ja_JP.arb
  lib/l10n/ko_KR/app_ko_KR.arb
  lib/l10n/lt_LT/app_lt_LT.arb
  lib/l10n/lv_LV/app_lv_LV.arb
  lib/l10n/nl_NL/app_nl_NL.arb
  lib/l10n/no_NO/app_no_NO.arb
  lib/l10n/pl_PL/app_pl_PL.arb
  lib/l10n/pt_BR/app_pt_BR.arb
  lib/l10n/pt_PT/app_pt_PT.arb
  lib/l10n/ro_RO/app_ro_RO.arb
  lib/l10n/ru_RU/app_ru_RU.arb
  lib/l10n/sk_SK/app_sk_SK.arb
  lib/l10n/sl_SI/app_sl_SI.arb
  lib/l10n/sr_CS/app_sr_CS.arb
  lib/l10n/sv_SE/app_sv_SE.arb
  lib/l10n/th_TH/app_th_TH.arb
  lib/l10n/tr_TR/app_tr_TR.arb
  lib/l10n/uk_UA/app_uk_UA.arb
  lib/l10n/vi_VN/app_vi_VN.arb
  lib/l10n/zh_CN/app_zh_CN.arb
  lib/l10n/zh_TW/app_zh_TW.arb
Labels: translation

#657 New Crowdin updates
  lib/l10n/ar_SA/app_ar_SA.arb
  lib/l10n/bg_BG/app_bg_BG.arb
  lib/l10n/cs_CZ/app_cs_CZ.arb
  lib/l10n/da_DK/app_da_DK.arb
  lib/l10n/de_DE/app_de_DE.arb
  lib/l10n/el_GR/app_el_GR.arb
  lib/l10n/es_ES/app_es_ES.arb
  lib/l10n/es_MX/app_es_MX.arb
  lib/l10n/et_EE/app_et_EE.arb
  lib/l10n/fa_IR/app_fa_IR.arb
  lib/l10n/fi_FI/app_fi_FI.arb
  lib/l10n/fr_FR/app_fr_FR.arb
  lib/l10n/he_IL/app_he_IL.arb
  lib/l10n/hi_IN/app_hi_IN.arb
  lib/l10n/hu_HU/app_hu_HU.arb
  lib/l10n/id_ID/app_id_ID.arb
  lib/l10n/it_IT/app_it_IT.arb
  lib/l10n/ja_JP/app_ja_JP.arb
  lib/l10n/ko_KR/app_ko_KR.arb
  lib/l10n/lt_LT/app_lt_LT.arb
  lib/l10n/lv_LV/app_lv_LV.arb
  lib/l10n/nl_NL/app_nl_NL.arb
  lib/l10n/no_NO/app_no_NO.arb
  lib/l10n/pl_PL/app_pl_PL.arb
  lib/l10n/pt_BR/app_pt_BR.arb
  lib/l10n/pt_PT/app_pt_PT.arb
  lib/l10n/ro_RO/app_ro_RO.arb
  lib/l10n/ru_RU/app_ru_RU.arb
  lib/l10n/sk_SK/app_sk_SK.arb
  lib/l10n/sl_SI/app_sl_SI.arb
  lib/l10n/sr_CS/app_sr_CS.arb
  lib/l10n/sv_SE/app_sv_SE.arb
  lib/l10n/th_TH/app_th_TH.arb
  lib/l10n/tr_TR/app_tr_TR.arb
  lib/l10n/uk_UA/app_uk_UA.arb
  lib/l10n/vi_VN/app_vi_VN.arb
  lib/l10n/zh_CN/app_zh_CN.arb
  lib/l10n/zh_TW/app_zh_TW.arb
Labels: translation

#659 New Crowdin updates
  lib/l10n/fr_FR/app_fr_FR.arb
  lib/l10n/tr_TR/app_tr_TR.arb
Labels: translation

#641 Use FVM in GitHub Actions and migrate to Flutter 3.32.4
  .fvmrc
  .github/workflows/android.yaml
  .github/workflows/ci.yaml
  .github/workflows/ios.yaml
  .gitignore
  BUILDING.md
  analysis_options.yaml
  android/.gitignore
  docs/android_studio_fvm.png
  ios/.gitignore
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner.xcworkspace/xcshareddata/swiftpm/Package.resolved
  lib/api.dart
  lib/api_form.dart
  lib/barcode/barcode.dart
  lib/barcode/camera_controller.dart
  lib/inventree/model.dart
  lib/main.dart
  lib/settings/app_settings.dart
  lib/settings/barcode_settings.dart
  lib/widget/dialogs.dart
  lib/widget/part/part_suppliers.dart
  pubspec.lock
  pubspec.yaml
  tasks.py
Labels: documentation, CI
